### ISSUE TITLE
Avaluació exercicis de base de dades

### ISSUE THREAD

**Issue by joanpardogine** [MarcBouzas/Exercicis_MP02_UF03#1]
Hola @MarcBouzas,

No veig que hi hagi res pujat?

Si tens cap dubte, pregunta-m'ho i t'ajudo!

Joan

**Comment by joanpardogine** [comment]
Hola @MarcBouzas,

El **divendres 9 d'abril**, vaig crear un **```issue```** (*```No hi ha res! #1```*) a on et deia que no veia cap dels enunciats que us demanava.

![image](https://user-images.githubusercontent.com/63462877/115116524-39e4ad80-9f9a-11eb-8835-2c03e681338e.png)

I no em dius res.

El **dijous 15 d'abril**, t'envio un correu electrònic a on et comento que m'indiquis a on són els exercicis que us vaig demanar.

![image](https://user-images.githubusercontent.com/63462877/115116574-757f7780-9f9a-11eb-8296-759307dfbb82.png)

I tornes a no dir-me res.

# Enunciat 9
> No he trobat cap exercici amb el codi per executar aquest enunciat.

# Enunciat 11
> No he trobat cap exercici amb el codi per executar aquest enunciat.

# Enunciat 12
> No he trobat cap exercici amb el codi per executar aquest enunciat.

# Enunciat 13
> No he trobat cap exercici amb el codi per executar aquest enunciat.

Si us plau, em pots dir quina nota creus que t'he de posar davant d'aquesta situació.

Ja em diràs.
Bon cap de setmana.

Joan

**Comment by MarcBouzas** [comment]
Emm, Si que ho vaig pujar, ho vaig ficar dins de una carpeta,la que es diu
activitats cursors
https://github.com/MarcBouzas/Exercicis_MP02_UF03/tree/main/(M02)UF3.%20ActivitatsCursors

Missatge de joanpardogine ***@***.***> del dia ds., 17 d’abr.
2021 a les 16:39:

**Comment by joanpardogine** [comment]
Hola @MarcBouzas,

tens raó, ho sento, no l'havia actualitzat.

![image](https://user-images.githubusercontent.com/63462877/115127541-96b28900-9fd7-11eb-8191-eada9f32be6f.png)

# Enunciat 8
He executat el següent fitxer [BouzasMarc_Act_03_ProcEmm_MySQL_Apartat_008](https://github.com/MarcBouzas/Exercicis_MP02_UF03/blob/main/(M02)UF3.%20ActivitatsCursors/BouzasMarc_Act_03_ProcEmm_MySQL_Apartat_008.sql)

I he rebut el següent:

```sql
mysql> call act8();
ERROR 1054 (42S22): Unknown column 'presspost_peli' in 'field list'
```

> Segons sembla hi ha algun error. Si us plau, pots mirar de solucionar-lo. O com 
> a mínim esbrina que pots estar passant.

# Enunciat 9
He executat el següent fitxer [BouzasMarc_Act_03_ProcEmm_MySQL_Apartat_009.sql](https://github.com/MarcBouzas/Exercicis_MP02_UF03/blob/main/(M02)UF3.%20ActivitatsCursors/BouzasMarc_Act_03_ProcEmm_MySQL_Apartat_009.sql)

I he rebut el següent:

```sql
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recap BIGINT DEFAULT 0;
   DECALRE press BIGINT DEFAULT 0;
   
   DECLARE elcurs' at line 7
```

> Segons sembla hi ha algun error. Si us plau, pots mirar de solucionar-lo. O com 
> a mínim esbrina que pots estar passant.


# Enunciat 11
He executat el següent fitxer [BouzasMarc_Act_03_ProcEmm_MySQL_Apartat_011.sql](https://github.com/MarcBouzas/Exercicis_MP02_UF03/blob/main/(M02)UF3.%20ActivitatsCursors/BouzasMarc_Act_03_ProcEmm_MySQL_Apartat_011.sql)

I el resultat ha estat aquest:
```sql
mysql> select act11(4);
+----------+
| act11(4) |
+----------+
|        3 |
+----------+
1 row in set (0.00 sec)
```
> Segons aquest resultat, veig que has copiat el text que hi ha al document que conté
> els enunciats. I el resultat no és el que demana l'enunciat.
> No tinc clar si ho recordes, però us vaig comentar a classe que el codi que vaig escriure
> no era correcte, per tant que no el féssiu servir. Tot i la meva advertència, l'has copiat i
> enganxat, sense ni tan sols mirar el que demanava l'enunciat, ni el que feia el codi. :(

# Enunciat 12
> No he trobat cap exercici amb el codi per executar aquest enunciat.

# Enunciat 13
> No he trobat cap exercici amb el codi per executar aquest enunciat.

Si us plau, em pots dir quina nota creus que t'he de posar davant d'aquesta situació.

Ja em diràs.
Bon cap de setmana.

Joan
